arg version
from almalinux:${version:-9}
env COURSE="devops" \
    DURATION="120hours"
arg TRAINER="myself"
run echo "Hi, COURSE is ${COURSE}, DURATION is ${DURATION}, and TRAINER is ${TRAINER}"
cmd ["sleep", "1000"]